development:
  adapter: postgresql
  encoding: unicode
  database: effy_development
  pool: 5
  host: localhost
  username: mathildathompson
  password:

# production:
#   adapter: postgresql
#   encoding: unicode
#   database: effy_production
#   pool: 5
#   password:
